// <auto-generated />
using System;
using DynamicTrafficLightServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicTrafficLightServer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicTrafficLightServer.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DefaultGreenTime")
                        .HasColumnType("int");

                    b.Property<int>("DefaultRedTime")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("MaxGreenTime")
                        .HasColumnType("int");

                    b.Property<int>("MinGreenTime")
                        .HasColumnType("int");

                    b.Property<string>("SequenceGreenTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimePerVehicle")
                        .HasColumnType("int");

                    b.Property<int>("TrafficLightId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.HasIndex("TrafficLightId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.EntityChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("ChangedById")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.ToTable("EntityChangeLogs");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.Intersection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable("Intersections");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.TrafficLight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("IntersectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastUpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("IntersectionId");

                    b.HasIndex("LastUpdatedById");

                    b.ToTable("TrafficLights");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.TrafficSwitchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GreenLightDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("InitById")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrafficLightId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InitById");

                    b.HasIndex("TrafficLightId");

                    b.ToTable("TrafficSwitchLogs");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthIdentityId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthIdentityId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthIdentityId = "system",
                            Name = "System"
                        });
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.Configuration", b =>
                {
                    b.HasOne("DynamicTrafficLightServer.Models.User", "CreatedBy")
                        .WithMany("CreatedConfigurations")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DynamicTrafficLightServer.Models.User", "LastUpdatedBy")
                        .WithMany("LastUpdateConfigurations")
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DynamicTrafficLightServer.Models.TrafficLight", "TrafficLight")
                        .WithMany("Configurations")
                        .HasForeignKey("TrafficLightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");

                    b.Navigation("TrafficLight");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.EntityChangeLog", b =>
                {
                    b.HasOne("DynamicTrafficLightServer.Models.User", "ChangedBy")
                        .WithMany("EntityChangeLogs")
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.Intersection", b =>
                {
                    b.HasOne("DynamicTrafficLightServer.Models.User", "CreatedBy")
                        .WithMany("CreatedIntersections")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DynamicTrafficLightServer.Models.User", "LastUpdatedBy")
                        .WithMany("LastUpdatedIntersections")
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.TrafficLight", b =>
                {
                    b.HasOne("DynamicTrafficLightServer.Models.User", "CreatedBy")
                        .WithMany("CreatedTrafficLights")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DynamicTrafficLightServer.Models.Intersection", "Intersection")
                        .WithMany("TrafficLights")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DynamicTrafficLightServer.Models.User", "LastUpdatedBy")
                        .WithMany("LastUpdatedTrafficLights")
                        .HasForeignKey("LastUpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Intersection");

                    b.Navigation("LastUpdatedBy");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.TrafficSwitchLog", b =>
                {
                    b.HasOne("DynamicTrafficLightServer.Models.User", "InitBy")
                        .WithMany("TrafficSwitchLogs")
                        .HasForeignKey("InitById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DynamicTrafficLightServer.Models.TrafficLight", "TrafficLight")
                        .WithMany("TrafficSwitchLogs")
                        .HasForeignKey("TrafficLightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InitBy");

                    b.Navigation("TrafficLight");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.Intersection", b =>
                {
                    b.Navigation("TrafficLights");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.TrafficLight", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("TrafficSwitchLogs");
                });

            modelBuilder.Entity("DynamicTrafficLightServer.Models.User", b =>
                {
                    b.Navigation("CreatedConfigurations");

                    b.Navigation("CreatedIntersections");

                    b.Navigation("CreatedTrafficLights");

                    b.Navigation("EntityChangeLogs");

                    b.Navigation("LastUpdateConfigurations");

                    b.Navigation("LastUpdatedIntersections");

                    b.Navigation("LastUpdatedTrafficLights");

                    b.Navigation("TrafficSwitchLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
